# Until https://github.com/julia-actions/julia-uploadcodecov/issues/1 get fixed
# submit coverage report via travis
language: julia
os:
  - linux
julia:
  - 1.0
notifications:
  email: false
cache:
  directories:
    - $HOME/.julia/artifacts
codecov: true
